export const servicesData = [
  {
    slug: "ai-front-desk",
    title: "AI Front Desk",
    tagline: "Never miss a lead again.",
    heroImg: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1400&q=80&fit=crop",
    problem: "Most service businesses lose 30–40% of potential customers to missed calls, slow responses, and unanswered website inquiries — especially after hours. Every missed call is a lead that called your competitor instead.",
    solution: "We deploy an AI system that answers every inquiry, texts back missed calls in under 60 seconds, handles website chat, qualifies leads, and books appointments — around the clock, with no extra staff needed.",
    steps: [
      { step: "01", title: "Map Your Intake Points", desc: "We document every way a customer can reach you — phone, website, social — and identify exactly where leads are slipping through." },
      { step: "02", title: "Build Your AI Receptionist", desc: "We configure your AI with your services, pricing, hours, and booking rules. It knows your business as well as your best staff member." },
      { step: "03", title: "Launch & Monitor", desc: "Go live in 4–6 weeks. Every conversation is logged. You see every lead captured, every booking made, every question answered." },
    ],
    metrics: [
      { value: "< 60s", label: "Response time to every inquiry" },
      { value: "3–5×", label: "More leads captured after hours" },
      { value: "24/7", label: "Coverage with no extra staff" },
      { value: "40%", label: "Fewer no-shows with automated reminders" },
    ],
    industries: ["Restaurants & Cafes", "Grooming & Pet Care", "Landscaping", "Contractors", "Med Spas", "Clinics"],
    tech: ["Retell AI", "Twilio", "Supabase", "Next.js", "OpenAI"],
    cta: "Stop losing customers to voicemail. Your AI receptionist is ready in 4 weeks.",
  },
  {
    slug: "ai-follow-up",
    title: "AI Follow-Up Engine",
    tagline: "No lead ever goes cold.",
    heroImg: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1400&q=80&fit=crop",
    problem: "Most businesses follow up on fewer than half their leads — not because they don't want to, but because there isn't enough time. Quotes go cold. Appointments get forgotten. Old customers never hear from you again.",
    solution: "Automated sequences follow up on every inquiry, confirm appointments, send review requests, chase quotes, and reactivate old customers — on a schedule that would be impossible to manage manually.",
    steps: [
      { step: "01", title: "Map Your Follow-Up Gaps", desc: "We identify every point where leads go cold — unread inquiries, unconfirmed bookings, unsent review requests, dormant customers." },
      { step: "02", title: "Build Automated Sequences", desc: "We build multi-step SMS and email sequences for each scenario — timed, personalized, and triggered automatically by customer actions." },
      { step: "03", title: "Launch & Optimize", desc: "Sequences go live in 3–4 weeks. We monitor open rates, reply rates, and booking conversions and tune based on real results." },
    ],
    metrics: [
      { value: "40%", label: "Reduction in no-shows" },
      { value: "2×", label: "More reviews collected per month" },
      { value: "100%", label: "Of leads followed up automatically" },
      { value: "30%", label: "More repeat bookings from reactivation" },
    ],
    industries: ["Restaurants & Cafes", "Grooming & Pet Care", "Landscaping", "Contractors", "Med Spas", "Clinics"],
    tech: ["Twilio SMS", "Supabase", "Next.js", "OpenAI", "Cron automation"],
    cta: "Every lead deserves a follow-up. Automate it once, benefit forever.",
  },
  {
    slug: "ai-operations",
    title: "AI Operations Assistant",
    tagline: "Your back-office, automated.",
    heroImg: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=80&fit=crop",
    problem: "Service businesses lose 10–15 hours per week to repetitive admin — updating records, routing requests, assigning staff, generating reports. This work doesn't require human judgment. It just takes time that could be spent on customers.",
    solution: "Routine admin workflows — CRM updates, request routing, staff assignments, daily summaries, crew scheduling — run automatically. Your team focuses on customers, not paperwork.",
    steps: [
      { step: "01", title: "Audit Your Admin Workflows", desc: "We spend time with your team documenting every repetitive task — what triggers it, what data it needs, and what output it produces." },
      { step: "02", title: "Automate the Right Things", desc: "We build automation pipelines for your highest-volume tasks — the ones your team does every single day without thinking." },
      { step: "03", title: "Connect Your Tools", desc: "We integrate with your existing systems — scheduling tools, CRMs, Sheets — so data flows automatically without manual entry." },
    ],
    metrics: [
      { value: "10+ hrs", label: "Saved per week per business" },
      { value: "0", label: "Manual CRM updates needed" },
      { value: "Real-time", label: "Dashboard visibility on crew & jobs" },
      { value: "95%", label: "Reduction in missed task follow-up" },
    ],
    industries: ["Landscaping", "Contractors", "Grooming & Pet Care", "Restaurants", "Med Spas", "Clinics"],
    tech: ["Supabase", "Next.js", "Twilio", "OpenAI", "Cron jobs"],
    cta: "Give your team their time back. Automate the work that doesn't need a human.",
  },
  {
    slug: "social-scheduling",
    title: "Social Scheduling & Content",
    tagline: "Post every day without lifting a finger.",
    heroImg: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1400&q=80&fit=crop",
    problem: "Most local businesses know they should be posting on social media every day — but between running the business, managing staff, and serving customers, it never happens. A dead Instagram profile costs you customers who check before they book.",
    solution: "AI writes your social captions, schedules posts to Instagram, Facebook, and TikTok, fires SMS campaigns to your customer list, and keeps your marketing calendar full — completely on autopilot.",
    steps: [
      { step: "01", title: "Connect Your Accounts", desc: "We connect your Instagram, Facebook, and TikTok in one place. Takes 10 minutes." },
      { step: "02", title: "AI Learns Your Business", desc: "Tell it your services, specials, or events. AI writes captions, picks hashtags, and schedules at the best posting times." },
      { step: "03", title: "Watch It Run", desc: "Posts go out automatically. SMS campaigns fire on schedule. You see performance data in your dashboard — reach, engagement, clicks." },
    ],
    metrics: [
      { value: "7×", label: "More consistent posting vs manual" },
      { value: "5 min", label: "To schedule a week of content" },
      { value: "100%", label: "Of SMS campaigns sent on time" },
      { value: "3×", label: "More engagement vs irregular posting" },
    ],
    industries: ["Restaurants & Cafes", "Grooming & Pet Care", "Landscaping", "Contractors", "Med Spas", "Retail"],
    tech: ["Meta Graph API", "TikTok API", "Twilio SMS", "Supabase", "OpenAI"],
    cta: "Your competitors post every day. Now you can too — without doing it yourself.",
  },
  {
    slug: "ai-advertising",
    title: "AI Advertising",
    tagline: "Turn $5/day into new customers.",
    heroImg: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1400&q=80&fit=crop",
    problem: "Running Facebook and Google ads manually is a full-time job — and most local businesses either don't do it or waste money targeting the wrong people. 40% of ad budgets are spent showing ads to people who will never become customers.",
    solution: "AI-powered Meta and Google Ads targeted to people within miles of your business. AI writes the copy, generates ad creative, picks the audience, and optimizes spend automatically — so your budget goes to people most likely to walk through your door.",
    steps: [
      { step: "01", title: "Connect Your Ad Accounts", desc: "We connect your Meta Business Manager and Google Ads account. We handle the technical setup completely." },
      { step: "02", title: "AI Builds Your Campaign", desc: "AI generates ad copy, creative, and audience segments targeted within your ideal radius. You approve before anything goes live." },
      { step: "03", title: "Optimize & Scale", desc: "AI monitors performance daily, shifts budget to what's working, and surfaces insights in your dashboard. Scale up what converts." },
    ],
    metrics: [
      { value: "84%", label: "Lower cost per customer vs unoptimized ads" },
      { value: "5 mi", label: "Hyper-local targeting radius" },
      { value: "$5/day", label: "Minimum to get started" },
      { value: "22 min", label: "To launch your first AI campaign" },
    ],
    industries: ["Restaurants & Cafes", "Grooming & Pet Care", "Landscaping", "Contractors", "Med Spas", "Retail"],
    tech: ["Meta Marketing API", "Google Ads API", "OpenAI", "Next.js", "Supabase"],
    cta: "Stop guessing who to target. Let AI put your ads in front of your ideal local customers.",
  },
  {
    slug: "ai-strategy",
    title: "AI Strategy & Consulting",
    tagline: "Know exactly where AI creates value in your business.",
    heroImg: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1400&q=80&fit=crop",
    problem: "Most businesses don't know where to start with AI — or they've tried generic tools and seen no real return. Without a clear strategy, you waste money on the wrong things and miss the opportunities that would actually change your operations.",
    solution: "We audit your business, identify where AI will genuinely create value, and give you a clear roadmap. Honest assessment — no hype, no vendor bias. Just a prioritized plan for what to build, in what order.",
    steps: [
      { step: "01", title: "Business Audit", desc: "We interview your team and map every workflow to understand where time and revenue are being lost — and which problems AI can actually solve." },
      { step: "02", title: "Opportunity Scoring", desc: "We rank every AI opportunity by ROI potential, implementation effort, and strategic importance — so you invest in what matters first." },
      { step: "03", title: "Roadmap Delivery", desc: "You receive a prioritized action plan with project scopes, budget estimates, and a phased delivery timeline. Delivered in 2 weeks." },
    ],
    metrics: [
      { value: "2 weeks", label: "From audit to full strategy delivery" },
      { value: "100%", label: "Unbiased — we recommend what's right" },
      { value: "3–5×", label: "Typical ROI on strategy investment" },
      { value: "Free", label: "First 30-min call to assess fit" },
    ],
    industries: ["Any service business", "Restaurants", "Grooming", "Landscaping", "Contractors", "Med Spas"],
    tech: ["Technology-agnostic", "Process mapping", "ROI modelling"],
    cta: "Spend 2 weeks with us and walk away knowing exactly what AI can do for your business.",
  },
]

export const caseStudiesData = [
  {
    slug: "predictive-inventory",
    title: "Predictive Inventory AI",
    client: "Solution type: Retail & E-commerce",
    tag: "Retail • AI Automation",
    heroImg: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1400&q=80&fit=crop",
    challenge:
      "Multi-location retailers operating with a central warehouse commonly face a 20–25% stockout rate on fast-moving SKUs and significant overstock on seasonal items. Buying teams make decisions using week-old spreadsheet reports, causing lost revenue from stockouts and capital locked in unsold inventory.",
    solution:
      "We build machine learning demand forecasting systems that ingest point-of-sale data, weather, local event calendars, and competitor pricing signals to predict demand at the SKU × store level — updated every 24 hours — and automate the reorder process end-to-end.",
    whatWeDid: [
      "Unify disconnected data sources (POS, ERP, weather API, Google Trends, competitor data) into a single ML feature store",
      "Train a LightGBM ensemble model with store-specific seasonality, promotional uplift factors, and lead-time awareness",
      "Build an automated reorder engine that raises purchase orders directly in the ERP when stock falls below AI-predicted safety levels",
      "Create a real-time dashboard showing predicted stockout risk by store and SKU with 7-day and 30-day horizons",
      "Integrate SMS and email alerts for store managers when urgent replenishment is needed",
    ],
    results: [
      { metric: "Stockout rate", before: "~22% (industry avg)", after: "~6%", change: "↓ 70%" },
      { metric: "Overstock capital tied up", before: "High (manual ordering)", after: "Reduced significantly", change: "↓ 60–70%" },
      { metric: "Buying team hours/week", before: "100+ hrs manual", after: "~20 hrs review", change: "↓ 80%+" },
      { metric: "Forecast accuracy (MAPE)", before: "~30% error", after: "~8% error", change: "↑ 73%" },
      { metric: "Payback period", before: "—", after: "Typically 6–10 weeks", change: "Fast ROI" },
    ],
    timeline: "Typically 8 weeks from kick-off to production",
    tech: ["Python", "LightGBM", "Apache Airflow", "FastAPI", "React dashboard", "PostgreSQL", "AWS"],
    quote: "This type of system transforms the buying process from reactive guesswork to precision planning — reducing stockout losses and freeing the buying team for strategic decisions.",
    quoteAuthor: "What this means for your retail business",
  },
  {
    slug: "nlp-support-bot",
    title: "NLP Support Bot",
    client: "Solution type: SaaS & B2B Platforms",
    tag: "SaaS • Smart Chatbot",
    heroImg: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1400&q=80&fit=crop",
    challenge:
      "SaaS platforms with large customer bases typically face a situation where support teams handle thousands of tickets per day — 70–80% of which are the same 30–40 questions repeated over and over. Average first response time runs 4–8 hours, CSAT scores suffer, and hiring more agents is economically unsustainable.",
    solution:
      "We build LLM-powered support bots with a RAG pipeline over your entire documentation, knowledge base, and resolved ticket history — capable of understanding natural language questions, looking up account-specific data, and resolving issues end-to-end without human intervention.",
    whatWeDid: [
      "Process and embed documentation pages, resolved tickets, and SOPs into a vector database for accurate retrieval",
      "Build a multi-step reasoning agent that can query CRMs, check account status, reset features, and trigger actions — not just answer questions",
      "Integrate across Intercom, email, and in-app help widgets simultaneously with a single deployment",
      "Build human escalation flows that transfer full context so agents never ask customers to repeat themselves",
      "Create analytics dashboards tracking resolution rate, escalation reasons, and satisfaction by query category",
    ],
    results: [
      { metric: "Tickets handled by AI", before: "0% automated", after: "80–90% automated", change: "↑ 80+ pts" },
      { metric: "First response time", before: "4–8 hours", after: "< 2 seconds", change: "↓ 99.9%" },
      { metric: "Support cost per ticket", before: "High (human agent)", after: "Fraction of original", change: "↓ 85–95%" },
      { metric: "CSAT score", before: "Typically 3.0–3.5/5", after: "4.5+/5 achievable", change: "↑ 40–50%" },
      { metric: "Payback period", before: "—", after: "Typically 4–8 weeks", change: "Fast ROI" },
    ],
    timeline: "Typically 6 weeks to full production deployment",
    tech: ["GPT-4o", "LangChain", "Pinecone", "Intercom SDK", "FastAPI", "React", "Stripe API"],
    quote: "The right AI support bot eliminates repetitive ticket load, gives customers instant answers, and lets your human agents focus exclusively on the complex problems that actually need human judgement.",
    quoteAuthor: "What this means for your support team",
  },
  {
    slug: "vision-qa",
    title: "Vision QA System",
    client: "Solution type: Manufacturing & Production",
    tag: "Manufacturing • Computer Vision",
    heroImg: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=1400&q=80&fit=crop",
    challenge:
      "Manufacturers running visual quality inspection with human inspectors face well-documented limitations: eye fatigue after 90–120 minutes causes missed defects, throughput is capped by human speed, coverage is sample-based not 100%, and defects that escape to customers trigger costly recalls and warranty claims.",
    solution:
      "We deploy real-time computer vision systems across production lines — cameras at every quality gate, with custom-trained object detection models identifying defect types at production line speeds. 100% coverage, zero fatigue, automated rejection of non-conforming parts.",
    whatWeDid: [
      "Design and install industrial camera arrays at critical inspection points along production lines",
      "Collect and label training images covering all defect types across varying lighting and orientation conditions",
      "Train and optimise YOLOv9 / custom vision models for edge deployment on NVIDIA Jetson devices at each station",
      "Build real-time alerting and automated rejection — defective parts trigger air ejectors automatically",
      "Create quality dashboards with live defect rates by line, shift, and defect type — integrating with ERP systems",
    ],
    results: [
      { metric: "Defect escape rate", before: "1.5–2% (human inspection)", after: "< 0.1%", change: "↓ 90–95%" },
      { metric: "Inspection cost/shift", before: "High (dedicated inspectors)", after: "Near zero (automated)", change: "↓ 90%+" },
      { metric: "Throughput speed", before: "Human-limited", after: "Full line speed", change: "↑ 40–60%" },
      { metric: "Coverage", before: "Sample-based (~5%)", after: "100% of output", change: "↑ 20× coverage" },
      { metric: "Payback period", before: "—", after: "Typically 3–6 months", change: "One recall avoided pays for it" },
    ],
    timeline: "Typically 10 weeks including hardware installation",
    tech: ["YOLOv9", "PyTorch", "NVIDIA Jetson Orin", "OpenCV", "FastAPI", "InfluxDB", "Grafana"],
    quote: "Automated vision inspection eliminates the #1 source of quality escapes — human fatigue — and turns every camera on your line into a tireless, sub-millisecond quality decision-maker.",
    quoteAuthor: "What this means for your production line",
  },
  {
    slug: "fraud-detection",
    title: "Fraud Detection Engine",
    client: "Solution type: Fintech & Payments",
    tag: "Fintech • Machine Learning",
    heroImg: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1400&q=80&fit=crop",
    challenge:
      "Digital payments platforms relying on rule-based fraud systems face a fundamental tradeoff: rules tuned to catch fraud also block 3–5% of legitimate transactions (costing customers and revenue), while sophisticated fraud patterns — especially coordinated fraud rings — remain completely invisible to static rules.",
    solution:
      "We build real-time ML fraud detection systems that score every transaction in under 80ms using behavioural signals, graph relationships between accounts, and anomaly detection — replacing static rule engines with adaptive models that improve continuously as new patterns emerge.",
    whatWeDid: [
      "Analyse transaction history to identify fraud patterns invisible to rule-based systems",
      "Build graph neural networks modelling relationships between accounts, devices, and payment flows to detect coordinated fraud rings",
      "Train XGBoost ensembles on 200+ behavioural and contextual features per transaction",
      "Deploy behind a sub-80ms API endpoint capable of handling hundreds of transactions per second at peak",
      "Build an explainability layer so compliance teams understand every flagged transaction — essential for regulatory audits",
    ],
    results: [
      { metric: "Fraud loss reduction", before: "Rule-based, high losses", after: "80–90% reduction typical", change: "↓ 85%+" },
      { metric: "False positive rate", before: "3–5% legitimate blocked", after: "< 0.5%", change: "↓ 90%" },
      { metric: "Detection latency", before: "Manual review: hours", after: "< 80ms per transaction", change: "Real-time" },
      { metric: "Fraud ring detection", before: "0 (undetectable by rules)", after: "Fully detectable", change: "↑ New capability" },
      { metric: "Payback period", before: "—", after: "Typically weeks to 3 months", change: "High ROI" },
    ],
    timeline: "Typically 12 weeks including compliance review",
    tech: ["XGBoost", "Graph Neural Networks", "PyTorch", "Redis", "FastAPI", "Kafka", "AWS SageMaker"],
    quote: "A well-built ML fraud system doesn't just reduce losses — it gives your compliance team explainable decisions, unlocks fraud ring detection that rules can never see, and improves automatically as your transaction patterns evolve.",
    quoteAuthor: "What this means for your payments platform",
  },
  {
    slug: "geo-ai-advertising",
    title: "Geo-Targeted AI Advertising",
    client: "AdReach Media — Hyperlocal Advertising Platform",
    tag: "Advertising • Location AI",
    heroImg: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1400&q=80&fit=crop",
    challenge:
      "AdReach helped 200+ local businesses run ads across cities. Their biggest problem: they spent the same budget advertising to people 80 km away as to people 2 km away. No system knew which audience segment in which neighbourhood was actually converting. 40% of every ad budget was invisible money — spent, but never tracked to a real customer walking through a door.",
    solution:
      "We built an AI-powered geo-targeting engine that maps a business's ideal customer radius, scores every audience segment by location, behaviour, and buying intent, then dynamically routes ad spend to the highest-converting micro-zones — in real time. One campaign. One source. Precision delivery across every target city and neighbourhood.",
    whatWeDid: [
      "Built a location intelligence layer using GPS signals, neighbourhood income data, and foot-traffic patterns to score every 500m radius around a business",
      "Designed an AI audience-matching engine: given a source business profile, it identifies the 3–5 audience clusters most likely to convert — by location, time of day, and past purchase signals",
      "Created a dynamic budget-routing system that shifts ad spend in real time between geographic zones based on live conversion signals (store visits, calls, form fills)",
      "Built an interactive campaign map dashboard where business owners see exactly where their ads are showing, who's seeing them, and which locations are driving actual revenue",
      "Integrated with Meta Ads, Google Ads, and programmatic display networks — all controlled from a single AI-powered campaign manager",
      "Added cross-city expansion module: when a business opens a second location, AI auto-generates a new geo-targeted campaign using learnings from the first",
    ],
    results: [
      { metric: "Ad budget wasted on wrong zones", before: "40%", after: "6%", change: "↓ 85%" },
      { metric: "Cost per store visit (CPV)", before: "$5.10", after: "$0.82", change: "↓ 84%" },
      { metric: "Audience match accuracy", before: "51%", after: "94.3%", change: "↑ 85%" },
      { metric: "Campaign setup time", before: "3–4 days", after: "22 minutes", change: "↓ 96%" },
      { metric: "Revenue attributed to AI-routed ads", before: "$14K/month", after: "$68K/month", change: "↑ 383%" },
      { metric: "Businesses scaled to multi-city", before: "4", after: "67", change: "↑ 16× in 5 months" },
    ],
    timeline: "6 weeks from data connection to live campaigns",
    tech: ["Python", "Meta Marketing API", "Google Ads API", "PostGIS", "Redis", "Next.js", "OpenAI Embeddings", "Mapbox GL"],
    quote: "Before this, we were guessing which areas to target. Now the AI tells us exactly where to spend every dollar — and we can see it working on a live map. Our cost per customer dropped by 84% in 8 weeks.",
    quoteAuthor: "Karan Mehta, Founder — AdReach Media",
  },
]
